/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:40:39 GMT 2020
 */

package sg.edu.nus.comp.cs4218.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.exception.InvalidArgsException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class InvalidArgsException_ESTest extends InvalidArgsException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidArgsException invalidArgsException0 = new InvalidArgsException("$NN*`<zXJ0");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable((String) null);
      InvalidArgsException invalidArgsException0 = new InvalidArgsException("", mockThrowable0);
  }
}
