/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:41:40 GMT 2020
 */

package sg.edu.nus.comp.cs4218.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.exception.PwdException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PwdException_ESTest extends PwdException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PwdException pwdException0 = new PwdException("");
      PwdException pwdException1 = new PwdException(pwdException0, "");
      assertFalse(pwdException1.equals((Object)pwdException0));
  }
}
