/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:41:19 GMT 2020
 */

package sg.edu.nus.comp.cs4218.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.exception.SortException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SortException_ESTest extends SortException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SortException sortException0 = new SortException("");
      SortException sortException1 = new SortException(sortException0, "Problem sort from stdin: ");
      assertFalse(sortException1.equals((Object)sortException0));
  }
}
