/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:37:41 GMT 2020
 */

package generated;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.impl.app.CdApplication;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true)
public class CdApplication_ESTest extends CdApplication_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CdApplication cdApplication0 = new CdApplication();
      cdApplication0.changeToDirectory(".");
  }

}
