/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:38:31 GMT 2020
 */

package sg.edu.nus.comp.cs4218.impl.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.impl.parser.ArgsParser;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArgsParser_ESTest extends ArgsParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArgsParser argsParser0 = new ArgsParser();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "sg.edu.nus.comp.cs4218.exception.InvalidArgsException";
      stringArray0[1] = "dWc/p;!Uz";
      stringArray0[2] = "&c6r%?{=gX2M++[oqJ";
      // Undeclared exception!
      try { 
        argsParser0.parse(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.parser.ArgsParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArgsParser argsParser0 = new ArgsParser();
      argsParser0.validateArgs();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArgsParser argsParser0 = new ArgsParser();
      argsParser0.flags = null;
      // Undeclared exception!
      try { 
        argsParser0.validateArgs();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.HashSet", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArgsParser argsParser0 = new ArgsParser();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "-jSX#Y%X";
      stringArray0[1] = "illegal option -- ";
      stringArray0[2] = "illegal option -- ";
      stringArray0[3] = "illegal option -- ";
      try { 
        argsParser0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // illegal option -- S
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.parser.ArgsParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ArgsParser argsParser0 = new ArgsParser();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "";
      argsParser0.parse(stringArray0);
      assertEquals(1, stringArray0.length);
  }
}
