/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:39:53 GMT 2020
 */

package sg.edu.nus.comp.cs4218.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.exception.DateException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DateException_ESTest extends DateException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DateException dateException0 = new DateException("Could not write to output stream");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DateException dateException0 = new DateException((Exception) null, "Z6Y5<{zD=}N");
  }
}
