/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:36:10 GMT 2020
 */

package sg.edu.nus.comp.cs4218.impl.app.args;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.impl.app.args.WcArguments;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WcArguments_ESTest extends WcArguments_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "-z]V&.0Q'L)#X";
      try { 
        wcArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // wc: Invalid flag option supplied
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.WcArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "-vB'h=";
      try { 
        wcArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // wc: Invalid flag option supplied
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.WcArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      String[] stringArray0 = new String[2];
      stringArray0[0] = "-(8^J7Zo0`LA";
      try { 
        wcArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // wc: Invalid flag option supplied
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.WcArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "";
      stringArray0[1] = ",6h@3IX7";
      // Undeclared exception!
      try { 
        wcArguments0.parse(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "n\"n<WB.;TPpQ}8";
      wcArguments0.parse(stringArray0);
      List<String> list0 = wcArguments0.getFiles();
      assertTrue(wcArguments0.isWords());
      assertTrue(list0.contains("n\"n<WB.;TPpQ}8"));
      assertTrue(wcArguments0.isLines());
      assertTrue(wcArguments0.isBytes());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "wc: ";
      stringArray0[1] = "wc: ";
      stringArray0[2] = "W";
      stringArray0[3] = "dt";
      stringArray0[4] = "']@b>>woE0";
      stringArray0[5] = "sg.edu.nus.comp.cs4218.exception.WcException";
      stringArray0[6] = "wc: ";
      stringArray0[7] = "dt";
      stringArray0[8] = "~)-)W";
      wcArguments0.parse(stringArray0);
      assertTrue(wcArguments0.isLines());
      assertTrue(wcArguments0.isWords());
      assertTrue(wcArguments0.isBytes());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      String[] stringArray0 = new String[0];
      wcArguments0.parse(stringArray0);
      assertTrue(wcArguments0.isBytes());
      assertTrue(wcArguments0.isWords());
      assertTrue(wcArguments0.isLines());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      wcArguments0.parse((String[]) null);
      assertTrue(wcArguments0.isWords());
      assertTrue(wcArguments0.isLines());
      assertTrue(wcArguments0.isBytes());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      wcArguments0.getFiles();
      assertTrue(wcArguments0.isBytes());
      assertTrue(wcArguments0.isWords());
      assertTrue(wcArguments0.isLines());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      boolean boolean0 = wcArguments0.isWords();
      assertTrue(wcArguments0.isLines());
      assertTrue(wcArguments0.isBytes());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      boolean boolean0 = wcArguments0.isBytes();
      assertTrue(boolean0);
      assertTrue(wcArguments0.isWords());
      assertTrue(wcArguments0.isLines());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      WcArguments wcArguments0 = new WcArguments();
      boolean boolean0 = wcArguments0.isLines();
      assertTrue(wcArguments0.isBytes());
      assertTrue(boolean0);
      assertTrue(wcArguments0.isWords());
  }
}
