/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sun Mar 22 06:32:22 GMT 2020
 */

package sg.edu.nus.comp.cs4218.impl.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ApplicationRunner_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/7y/31bgr_m103sgjq41bs6b7r_m0000gq/T/"); 
    java.lang.System.setProperty("user.country", "CN"); 
    java.lang.System.setProperty("user.dir", "/Users/dr.fat/IdeaProjects/cs4218-project-ay1920-s2-2020-team6"); 
    java.lang.System.setProperty("user.home", "/Users/dr.fat"); 
    java.lang.System.setProperty("user.language", "zh"); 
    java.lang.System.setProperty("user.name", "dr.fat"); 
    java.lang.System.setProperty("user.timezone", "Asia/Singapore"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ApplicationRunner_ESTest_scaffolding.class.getClassLoader() ,
      "sg.edu.nus.comp.cs4218.exception.ShellException",
      "sg.edu.nus.comp.cs4218.app.RmInterface",
      "sg.edu.nus.comp.cs4218.impl.app.FindApplication",
      "sg.edu.nus.comp.cs4218.impl.parser.LsArgsParser",
      "sg.edu.nus.comp.cs4218.app.SedInterface",
      "sg.edu.nus.comp.cs4218.app.WcInterface",
      "sg.edu.nus.comp.cs4218.impl.app.args.SortArguments",
      "sg.edu.nus.comp.cs4218.app.EchoInterface",
      "sg.edu.nus.comp.cs4218.impl.app.SortApplication",
      "sg.edu.nus.comp.cs4218.impl.app.SedApplication",
      "sg.edu.nus.comp.cs4218.impl.app.EchoApplication",
      "sg.edu.nus.comp.cs4218.impl.app.CutApplication",
      "sg.edu.nus.comp.cs4218.exception.FindException",
      "sg.edu.nus.comp.cs4218.app.CdInterface",
      "sg.edu.nus.comp.cs4218.exception.LsException",
      "sg.edu.nus.comp.cs4218.impl.app.args.SedArguments",
      "sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner",
      "sg.edu.nus.comp.cs4218.exception.SedException",
      "sg.edu.nus.comp.cs4218.impl.app.PasteApplication",
      "sg.edu.nus.comp.cs4218.exception.EchoException",
      "sg.edu.nus.comp.cs4218.app.GrepInterface",
      "sg.edu.nus.comp.cs4218.impl.parser.RmArgsParser",
      "sg.edu.nus.comp.cs4218.app.SortInterface",
      "sg.edu.nus.comp.cs4218.exception.MvException",
      "sg.edu.nus.comp.cs4218.impl.parser.ArgsParser",
      "sg.edu.nus.comp.cs4218.app.ExitInterface",
      "sg.edu.nus.comp.cs4218.exception.InvalidArgsException",
      "sg.edu.nus.comp.cs4218.impl.app.args.CutArguments",
      "sg.edu.nus.comp.cs4218.exception.CutException",
      "sg.edu.nus.comp.cs4218.exception.InvalidDirectoryException",
      "sg.edu.nus.comp.cs4218.app.CutInterface",
      "sg.edu.nus.comp.cs4218.exception.GrepException",
      "sg.edu.nus.comp.cs4218.impl.app.LsApplication",
      "sg.edu.nus.comp.cs4218.app.PasteInterface",
      "sg.edu.nus.comp.cs4218.impl.parser.MvArgsParser",
      "sg.edu.nus.comp.cs4218.impl.app.CdApplication",
      "sg.edu.nus.comp.cs4218.exception.SortException",
      "sg.edu.nus.comp.cs4218.app.LsInterface",
      "sg.edu.nus.comp.cs4218.impl.app.MvApplication",
      "sg.edu.nus.comp.cs4218.exception.RmException",
      "sg.edu.nus.comp.cs4218.impl.app.RmApplication",
      "sg.edu.nus.comp.cs4218.Environment",
      "sg.edu.nus.comp.cs4218.Application",
      "sg.edu.nus.comp.cs4218.exception.AbstractApplicationException",
      "sg.edu.nus.comp.cs4218.impl.app.GrepApplication",
      "sg.edu.nus.comp.cs4218.impl.app.WcApplication",
      "sg.edu.nus.comp.cs4218.impl.app.args.WcArguments",
      "sg.edu.nus.comp.cs4218.app.MvInterface",
      "sg.edu.nus.comp.cs4218.exception.CdException",
      "sg.edu.nus.comp.cs4218.impl.app.ExitApplication",
      "sg.edu.nus.comp.cs4218.impl.util.StringUtils",
      "sg.edu.nus.comp.cs4218.exception.WcException",
      "sg.edu.nus.comp.cs4218.exception.PasteException",
      "sg.edu.nus.comp.cs4218.app.FindInterface"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.io.InputStream", false, ApplicationRunner_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("java.io.OutputStream", false, ApplicationRunner_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ApplicationRunner_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner",
      "sg.edu.nus.comp.cs4218.exception.ShellException",
      "sg.edu.nus.comp.cs4218.impl.app.WcApplication",
      "sg.edu.nus.comp.cs4218.impl.app.args.WcArguments",
      "sg.edu.nus.comp.cs4218.impl.util.IOUtils",
      "sg.edu.nus.comp.cs4218.Environment",
      "sg.edu.nus.comp.cs4218.impl.util.StringUtils",
      "sg.edu.nus.comp.cs4218.impl.app.FindApplication",
      "sg.edu.nus.comp.cs4218.exception.AbstractApplicationException",
      "sg.edu.nus.comp.cs4218.exception.FindException",
      "sg.edu.nus.comp.cs4218.impl.app.RmApplication",
      "sg.edu.nus.comp.cs4218.impl.parser.ArgsParser",
      "sg.edu.nus.comp.cs4218.impl.parser.RmArgsParser",
      "sg.edu.nus.comp.cs4218.impl.util.FileSystemUtils",
      "sg.edu.nus.comp.cs4218.exception.RmException",
      "sg.edu.nus.comp.cs4218.impl.app.CdApplication",
      "sg.edu.nus.comp.cs4218.exception.CdException",
      "sg.edu.nus.comp.cs4218.impl.app.GrepApplication",
      "sg.edu.nus.comp.cs4218.exception.GrepException",
      "sg.edu.nus.comp.cs4218.impl.app.SedApplication",
      "sg.edu.nus.comp.cs4218.impl.app.args.SedArguments",
      "sg.edu.nus.comp.cs4218.exception.SedException",
      "sg.edu.nus.comp.cs4218.impl.app.SortApplication",
      "sg.edu.nus.comp.cs4218.impl.app.args.SortArguments",
      "sg.edu.nus.comp.cs4218.exception.SortException",
      "sg.edu.nus.comp.cs4218.impl.app.PasteApplication",
      "sg.edu.nus.comp.cs4218.exception.PasteException",
      "sg.edu.nus.comp.cs4218.impl.app.ExitApplication",
      "sg.edu.nus.comp.cs4218.impl.app.MvApplication",
      "sg.edu.nus.comp.cs4218.impl.parser.MvArgsParser",
      "sg.edu.nus.comp.cs4218.exception.InvalidArgsException",
      "sg.edu.nus.comp.cs4218.impl.app.LsApplication",
      "sg.edu.nus.comp.cs4218.impl.parser.LsArgsParser",
      "sg.edu.nus.comp.cs4218.impl.app.CutApplication",
      "sg.edu.nus.comp.cs4218.impl.app.args.CutArguments",
      "sg.edu.nus.comp.cs4218.exception.CutException",
      "sg.edu.nus.comp.cs4218.impl.app.EchoApplication",
      "sg.edu.nus.comp.cs4218.exception.InvalidDirectoryException",
      "sg.edu.nus.comp.cs4218.exception.LsException",
      "sg.edu.nus.comp.cs4218.exception.MvException",
      "sg.edu.nus.comp.cs4218.exception.EchoException",
      "sg.edu.nus.comp.cs4218.exception.WcException"
    );
  }
}
