/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:33:37 GMT 2020
 */

package sg.edu.nus.comp.cs4218.impl.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner;
import sg.edu.nus.comp.cs4218.impl.util.ArgumentResolver;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArgumentResolver_ESTest extends ArgumentResolver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      List<String> list0 = argumentResolver0.resolveOneArgument("sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner");
      List<String> list1 = argumentResolver0.resolveOneArgument("dw~,T10R%Ei");
      List<String> list2 = argumentResolver0.parseArguments(list0);
      argumentResolver0.makeRegexArgument("^b@seB7N>iZug");
      List<String> list3 = argumentResolver0.parseArguments(list2);
      argumentResolver0.makeRegexArgument();
      List<String> list4 = argumentResolver0.resolveOneArgument("");
      argumentResolver0.parseArguments(list1);
      argumentResolver0.parseArguments(list4);
      argumentResolver0.resolveOneArgument("");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument("");
      List<String> list5 = argumentResolver0.parseArguments(list2);
      argumentResolver0.makeRegexArgument("sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner");
      argumentResolver0.makeRegexArgument("0$");
      List<String> list6 = argumentResolver0.resolveOneArgument("`L1{=:]y%\"(DiB>i,");
      argumentResolver0.parseArguments(list6);
      argumentResolver0.parseArguments(list3);
      argumentResolver0.parseArguments(list5);
      argumentResolver0.resolveOneArgument("`L1{=:]y%\"(DiB>i,");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument("");
      // Undeclared exception!
      try { 
        argumentResolver0.makeRegexArgument((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      ArgumentResolver argumentResolver1 = new ArgumentResolver();
      String string0 = "";
      List<String> list0 = argumentResolver0.resolveOneArgument("");
      List<String> list1 = argumentResolver1.parseArguments(list0);
      argumentResolver0.makeRegexArgument("");
      argumentResolver0.parseArguments(list1);
      argumentResolver0.resolveOneArgument("");
      argumentResolver1.makeRegexArgument();
      argumentResolver0.resolveOneArgument("u>%`");
      try { 
        argumentResolver1.resolveOneArgument("sG\"`_c`");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // shell: _c: Invalid app
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      List<String> list0 = argumentResolver0.resolveOneArgument("");
      List<String> list1 = argumentResolver0.parseArguments(list0);
      List<String> list2 = argumentResolver0.parseArguments(list1);
      argumentResolver0.makeRegexArgument("sg.edu.nus.comp.cs4218.exception.ShellException");
      List<String> list3 = argumentResolver0.resolveOneArgument("sg.edu.nus.comp.cs4218.exception.ShellException");
      argumentResolver0.parseArguments(list3);
      argumentResolver0.getAppRunner();
      argumentResolver0.makeRegexArgument();
      List<String> list4 = argumentResolver0.parseArguments(list3);
      argumentResolver0.resolveOneArgument("paste");
      argumentResolver0.parseArguments(list4);
      argumentResolver0.makeRegexArgument("sort");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.parseArguments(list0);
      argumentResolver0.resolveOneArgument("wc");
      argumentResolver0.resolveOneArgument("sg.edu.nus.comp.cs4218.exception.ShellException");
      argumentResolver0.resolveOneArgument("e");
      argumentResolver0.parseArguments(list2);
      argumentResolver0.getAppRunner();
      argumentResolver0.makeRegexArgument();
      argumentResolver0.getAppRunner();
      argumentResolver0.makeRegexArgument("sed");
      try { 
        argumentResolver0.resolveOneArgument("([^'\"`|<>;s]+|'[^']*'|\"([^\"`]*`.*?`[^\"`]*)+\"|\"[^\"]*\"|`[^`]*`)+");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // shell: ]*: Invalid app
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      List<String> list0 = argumentResolver0.resolveOneArgument("sg.edu.nus.comp.cs4218.impl.util.ArgumentResolver");
      List<String> list1 = argumentResolver0.parseArguments(list0);
      argumentResolver0.makeRegexArgument("R,Fz6V)RC");
      List<String> list2 = argumentResolver0.parseArguments(list1);
      argumentResolver0.makeRegexArgument("R,Fz6V)RC");
      argumentResolver0.resolveOneArgument("R,Fz6V)RC");
      List<String> list3 = argumentResolver0.parseArguments(list2);
      argumentResolver0.resolveOneArgument("1f_n:AV#gEV:=bN*");
      argumentResolver0.resolveOneArgument("sg.edu.nus.comp.cs4218.impl.util.ArgumentResolver");
      argumentResolver0.resolveOneArgument("R,Fz6V)RC");
      argumentResolver0.resolveOneArgument("vw'|CR`2QPcE0");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument("vw'|CR`2QPcE0");
      argumentResolver0.getAppRunner();
      argumentResolver0.parseArguments(list0);
      argumentResolver0.parseArguments(list3);
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument("");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.resolveOneArgument("|:A[_Oo;i`\"z&f+XEf");
      argumentResolver0.makeRegexArgument("s+");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument("|:A[_Oo;i`\"z&f+XEf");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument();
      List<String> list0 = argumentResolver0.resolveOneArgument("");
      argumentResolver0.parseArguments(list0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.makeRegexArgument("");
      argumentResolver0.resolveOneArgument("");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.getAppRunner();
      // Undeclared exception!
      try { 
        argumentResolver0.makeRegexArgument((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.makeRegexArgument();
      String string0 = "sUMUQ*KdR;7";
      argumentResolver0.makeRegexArgument();
      String string1 = "Invalid app";
      ArgumentResolver argumentResolver1 = new ArgumentResolver();
      // Undeclared exception!
      try { 
        argumentResolver1.resolveOneArgument((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.util.ArgumentResolver", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument();
      argumentResolver0.getAppRunner();
      ArgumentResolver argumentResolver1 = new ArgumentResolver();
      List<String> list0 = argumentResolver1.resolveOneArgument("Invalid app");
      List<String> list1 = argumentResolver1.resolveOneArgument("echo");
      argumentResolver0.parseArguments(list1);
      argumentResolver0.makeRegexArgument();
      argumentResolver0.getAppRunner();
      argumentResolver0.getAppRunner();
      argumentResolver0.getAppRunner();
      argumentResolver0.makeRegexArgument("");
      argumentResolver0.parseArguments(list0);
      argumentResolver1.makeRegexArgument();
      argumentResolver1.makeRegexArgument("");
      argumentResolver0.getAppRunner();
      argumentResolver0.getAppRunner();
      // Undeclared exception!
      try { 
        argumentResolver1.parseArguments((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.util.ArgumentResolver", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.makeRegexArgument("mU4202||VjcC");
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      List<String> list0 = argumentResolver0.resolveOneArgument("cut");
      argumentResolver0.parseArguments(list0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      // Undeclared exception!
      try { 
        argumentResolver0.parseArguments((List<String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.util.ArgumentResolver", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.resolveOneArgument("");
      argumentResolver0.resolveOneArgument("");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.resolveOneArgument("`LR_hdt48!F5Sg");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      ArgumentResolver argumentResolver1 = new ArgumentResolver();
      argumentResolver1.makeRegexArgument();
      argumentResolver0.resolveOneArgument("u>%`");
      try { 
        argumentResolver1.resolveOneArgument("sG\"`_c`");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // shell: _c: Invalid app
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      argumentResolver0.resolveOneArgument("|:A[_Oo;i`\"z&f+XEf");
      argumentResolver0.makeRegexArgument("Rs+");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.makeRegexArgument("|:A[_Oo;i`\"z&f+XEf");
      argumentResolver0.makeRegexArgument();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ArgumentResolver argumentResolver0 = new ArgumentResolver();
      List<String> list0 = argumentResolver0.resolveOneArgument("");
      List<String> list1 = argumentResolver0.parseArguments(list0);
      List<String> list2 = argumentResolver0.parseArguments(list1);
      argumentResolver0.makeRegexArgument("sg.edu.nus.comp.cs4218.exception.ShellException");
      List<String> list3 = argumentResolver0.resolveOneArgument("sg.edu.nus.comp.cs4218.exception.ShellException");
      List<String> list4 = argumentResolver0.parseArguments(list3);
      argumentResolver0.getAppRunner();
      argumentResolver0.makeRegexArgument();
      argumentResolver0.parseArguments(list4);
      argumentResolver0.makeRegexArgument("sort");
      argumentResolver0.makeRegexArgument();
      argumentResolver0.parseArguments(list0);
      argumentResolver0.resolveOneArgument("sg.edu.nus.comp.cs4218.exception.ShellException");
      argumentResolver0.resolveOneArgument("cut");
      argumentResolver0.parseArguments(list2);
      argumentResolver0.getAppRunner();
      argumentResolver0.makeRegexArgument();
      argumentResolver0.getAppRunner();
      argumentResolver0.makeRegexArgument("sed");
      try { 
        argumentResolver0.resolveOneArgument("([^'\"`|<>;s]+|'[^']*'|\"([^\"`]*`.*?`[^\"`]*)+\"|\"[^\"]*\"|`[^`]*`)+");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // shell: ]*: Invalid app
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.util.ApplicationRunner", e);
      }
  }
}
