/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 22 06:36:17 GMT 2020
 */

package sg.edu.nus.comp.cs4218.impl.app.args;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sg.edu.nus.comp.cs4218.impl.app.args.SedArguments;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SedArguments_ESTest extends SedArguments_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "uz%kJ$ue!~:' 6d0'C";
      try { 
        sedArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Invalid replacement rule
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "d}cr";
      try { 
        sedArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Invalid replacement rule
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SedArguments.validate("N.,.!", "", 960);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "sg.du.nus.comp.cs4218.impl.app.args.SedArguments";
      try { 
        sedArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // X needs to be a number greater than 0
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "s@YG?4%!u;BoO";
      try { 
        sedArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Invalid replacement rule
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "";
      try { 
        sedArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Invalid replacement rule
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String[] stringArray0 = new String[0];
      try { 
        sedArguments0.parse(stringArray0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // No replacement rule supplied
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String[] stringArray0 = new String[3];
      try { 
        sedArguments0.parse(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      try { 
        SedArguments.validate("rI*p(?", "rI*p(?", 4);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Invalid regular expression supplied
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      try { 
        SedArguments.validate("", "@9Bay>T0:~\"&p1", (-1));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // X needs to be a number greater than 0
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      try { 
        SedArguments.validate("", "", 9);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Regular expression cannot be empty
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      try { 
        SedArguments.validate("/Cet<Ll$Y<", (String) null, (-787));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Null arguments
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      try { 
        SedArguments.validate((String) null, (String) null, (-937));
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Null arguments
         //
         verifyException("sg.edu.nus.comp.cs4218.impl.app.args.SedArguments", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String string0 = sedArguments0.getRegex();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      int int0 = sedArguments0.getReplacementIndex();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      List<String> list0 = sedArguments0.getFiles();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SedArguments sedArguments0 = new SedArguments();
      String string0 = sedArguments0.getReplacement();
      assertNull(string0);
  }
}
